steps:
- task: ComponentGovernanceComponentDetection@0
  displayName: 🔍 Component Detection

- task: notice@0
  displayName: 🛠️ Generate NOTICE file
  inputs:
    outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
    outputformat: text
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: MicroBuildSigningPlugin@3
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: 🔧 Install MicroBuild Signing Plugin
  condition: and(succeeded(), or(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['SignType'], 'real')))

- task: MicroBuildSbomPlugin@1
  displayName: 🔧 Install MicroBuild Sbom Plugin
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- task: MicroBuildLocalizationPlugin@3
  inputs:
    languages: $(LocLanguages)
  displayName: 🔧 Install MicroBuild Localization Plugin
