trigger:
  batch: true
  branches:
    include:
    - main
    - 'v*'
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - azure-pipelines/release.yml
    - azure-pipelines/vs-insertion.yml
# Disable automatic real-signed builds and insertions
# because we mostly just maintain the repo compliance and freshness without making any shipping changes.
#schedules:
#- cron: "0 3 * * *" # Daily @ 8 PM PST
#  displayName: Daily vs-insertion
#  branches:
#    include:
#    - main
#    - 'v16.*'
#    - 'v17.*'

parameters:
- name: SignTypeSelection
  displayName: Sign type
  type: string
  default: Test
  values: [ 'Test', 'Real' ]
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: EnableCompliance
  displayName: Run Compliance Tools
  type: boolean
  default: true
- name: EnableAPIScan
  displayName: Include APIScan with Compliance tools
  type: boolean
  default: true

stages:

- stage: Build
  variables:
    MSBuildTreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    SignTypeSelection: ${{ parameters.SignTypeSelection }}
    Packaging.EnableSBOMSigning: false
    Codeql.Enabled: true

  jobs:
  - template: build.yml
    parameters:
      EnableCompliance: ${{ parameters.EnableCompliance }}
      EnableAPIScan: ${{ parameters.EnableAPIScan }}
      windowsPool: VSEngSS-MicroBuild2022-1ES
      includeMacOS: ${{ parameters.includeMacOS }}
      RunTests: ${{ parameters.RunTests }}

- template: prepare-insertion-stages.yml
